export const PUBLIC_KEY = 'Public';

export const JWT_CONSTANYS = {
  secret: 'secret',
};

export const LOGIC_STATUS = {
  SUCCESS: '0',
  FAIL: 'FAIL',
  SYSYEM_ERROR: 'SYSYEM_ERROR',
  PARAMETER_ERROR: 'PARAMETER_ERROR',
  BACKEND_APT_ERROR: 'BACKEND_APT_ERROR',
  TOKEN_ERROR: 'TOKEN_ERROR',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_ERROR: 'USER_ERROR',
  PERNISSION_ERROR: 'PERNISSION_ERROR',
};
